# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6.QtCore import QObject, Signal, Slot
from PyQt6 import QtCore, QtGui, QtWidgets
from src.interpret_output import resistance2NominalValueInPOhms

class Ui_MainWindow(QObject):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 670)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.resistorCategoriesList = QtWidgets.QListWidget(parent=self.centralwidget)
        self.resistorCategoriesList.setGeometry(QtCore.QRect(20, 50, 240, 125))
        self.resistorCategoriesList.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.resistorCategoriesList.setObjectName("resistorCategoriesList")
        item = QtWidgets.QListWidgetItem()
        self.resistorCategoriesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resistorCategoriesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resistorCategoriesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resistorCategoriesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resistorCategoriesList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.resistorCategoriesList.addItem(item)
        self.resistorCategoriesLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.resistorCategoriesLabel.setGeometry(QtCore.QRect(20, 20, 151, 20))
        self.resistorCategoriesLabel.setObjectName("resistorCategoriesLabel")
        self.inStockCheckBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.inStockCheckBox.setGeometry(QtCore.QRect(30, 190, 93, 26))
        self.inStockCheckBox.setChecked(True)
        self.inStockCheckBox.setObjectName("inStockCheckBox")
        self.relationInputBox = QtWidgets.QDoubleSpinBox(parent=self.centralwidget)
        self.relationInputBox.setGeometry(QtCore.QRect(20, 290, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.relationInputBox.setFont(font)
        self.relationInputBox.setDecimals(3)
        self.relationInputBox.setMaximum(1.0)
        self.relationInputBox.setSingleStep(0.1)
        self.relationInputBox.setObjectName("relationInputBox")
        self.relationInputLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.relationInputLabel.setGeometry(QtCore.QRect(20, 260, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.relationInputLabel.setFont(font)
        self.relationInputLabel.setObjectName("relationInputLabel")
        self.combosLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.combosLabel.setGeometry(QtCore.QRect(20, 350, 241, 16))
        self.combosLabel.setObjectName("combosLabel")
        self.rohsCompliantCheckBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.rohsCompliantCheckBox.setGeometry(QtCore.QRect(30, 220, 151, 26))
        self.rohsCompliantCheckBox.setObjectName("rohsCompliantCheckBox")
        self.searchButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.searchButton.setGeometry(QtCore.QRect(20, 570, 240, 41))
        self.searchButton.setObjectName("searchButton")
        self.filtersButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.filtersButton.setGeometry(QtCore.QRect(20, 510, 111, 29))
        self.filtersButton.setObjectName("filtersButton")
        self.resultsLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.resultsLabel.setGeometry(QtCore.QRect(280, 20, 151, 20))
        self.resultsLabel.setObjectName("resultsLabel")
        self.R1_Table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.R1_Table.setEnabled(True)
        self.R1_Table.setGeometry(QtCore.QRect(280, 50, 350, 560))
        self.R1_Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.R1_Table.setShowGrid(True)
        self.R1_Table.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.R1_Table.setObjectName("R1_Table")
        self.R1_Table.setColumnCount(1)
        self.R1_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.R1_Table.setHorizontalHeaderItem(0, item)
        self.R1_Table.horizontalHeader().setVisible(True)
        self.R1_Table.horizontalHeader().setCascadingSectionResizes(False)
        self.R1_Table.horizontalHeader().setDefaultSectionSize(349)
        self.R1_Table.horizontalHeader().setMinimumSectionSize(43)
        self.R1_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.R1_Label.setGeometry(QtCore.QRect(20, 390, 41, 20))
        self.R1_Label.setObjectName("R1_Label")
        self.L2_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.L2_Label.setGeometry(QtCore.QRect(20, 440, 41, 20))
        self.L2_Label.setObjectName("L2_Label")
        self.comboBox_R1 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_R1.setGeometry(QtCore.QRect(60, 385, 201, 31))
        self.comboBox_R1.setObjectName("comboBox_R1")
        self.comboBox_R2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboBox_R2.setGeometry(QtCore.QRect(60, 435, 201, 31))
        self.comboBox_R2.setObjectName("comboBox_R2")
        self.R2_Table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.R2_Table.setEnabled(True)
        self.R2_Table.setGeometry(QtCore.QRect(635, 50, 350, 560))
        self.R2_Table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.R2_Table.setShowGrid(True)
        self.R2_Table.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.R2_Table.setObjectName("R2_Table")
        self.R2_Table.setColumnCount(1)
        self.R2_Table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.R2_Table.setHorizontalHeaderItem(0, item)
        self.R2_Table.horizontalHeader().setVisible(True)
        self.R2_Table.horizontalHeader().setCascadingSectionResizes(False)
        self.R2_Table.horizontalHeader().setDefaultSectionSize(349)
        self.R2_Table.horizontalHeader().setMinimumSectionSize(43)
        self.finalVoltageRatioBox = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.finalVoltageRatioBox.setGeometry(QtCore.QRect(1010, 570, 175, 40))
        self.finalVoltageRatioBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.finalVoltageRatioBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.finalVoltageRatioBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.finalVoltageRatioBox.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustIgnored)
        self.finalVoltageRatioBox.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.finalVoltageRatioBox.setObjectName("finalVoltageRatioBox")
        self.devianceBox = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.devianceBox.setGeometry(QtCore.QRect(1010, 480, 175, 40))
        self.devianceBox.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.devianceBox.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.devianceBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.devianceBox.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.devianceBox.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByKeyboard|QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.devianceBox.setObjectName("devianceBox")
        self.devianceLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.devianceLabel.setGeometry(QtCore.QRect(1010, 455, 140, 20))
        self.devianceLabel.setObjectName("devianceLabel")
        self.finalVoltageRatioLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.finalVoltageRatioLabel.setGeometry(QtCore.QRect(1010, 545, 140, 20))
        self.finalVoltageRatioLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.finalVoltageRatioLabel.setObjectName("finalVoltageRatioLabel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        #####

        self.newCombo_R1_value = False
        self.newCombo_R2_value = False

        self.R1_SelectionExists = False
        self.R2_SelectionExists = False

        self.resistorCategoriesList.itemSelectionChanged.connect(self.basicCriteriaChanged)
        self.inStockCheckBox.stateChanged.connect(self.basicCriteriaChanged)
        self.rohsCompliantCheckBox.stateChanged.connect(self.rohsSelectionChanged)
        self.relationInputBox.valueChanged.connect(self.relationInputChanged)
        self.comboBox_R1.currentTextChanged.connect(self.comboBox_R1_Changed)
        self.comboBox_R2.currentTextChanged.connect(self.comboBox_R2_Changed)
        self.filtersButton.clicked.connect(self.filtersClicked)
        self.searchButton.clicked.connect(self.searchInitiated)
        self.R1_Table.itemSelectionChanged.connect(self.R1_SelectionChanged)
        self.R2_Table.itemSelectionChanged.connect(self.R2_SelectionChanged)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Pick-a-Res: Voltage Divider Calculator"))
        __sortingEnabled = self.resistorCategoriesList.isSortingEnabled()
        self.resistorCategoriesList.setSortingEnabled(False)
        item = self.resistorCategoriesList.item(0)
        item.setText(_translate("MainWindow", "Chassis Mount Resistors"))
        item = self.resistorCategoriesList.item(1)
        item.setText(_translate("MainWindow", "Chip Resistor - Surface Mount"))
        item = self.resistorCategoriesList.item(2)
        item.setText(_translate("MainWindow", "Precision Trimmed Resistors"))
        item = self.resistorCategoriesList.item(3)
        item.setText(_translate("MainWindow", "Resistor Networks - Arrays"))
        item = self.resistorCategoriesList.item(4)
        item.setText(_translate("MainWindow", "Specialized Resistors"))
        item = self.resistorCategoriesList.item(5)
        item.setText(_translate("MainWindow", "Through Hole Resistors"))
        self.resistorCategoriesList.setSortingEnabled(__sortingEnabled)
        self.resistorCategoriesLabel.setText(_translate("MainWindow", "Resistor Categories"))
        self.inStockCheckBox.setText(_translate("MainWindow", "In Stock"))
        self.relationInputLabel.setText(_translate("MainWindow", "Voltage Ratio"))
        self.combosLabel.setText(_translate("MainWindow", "Pick one of the resistances"))
        self.rohsCompliantCheckBox.setText(_translate("MainWindow", "RoHS Compliant"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.filtersButton.setText(_translate("MainWindow", "Filters"))
        self.resultsLabel.setText(_translate("MainWindow", "Results"))
        item = self.R1_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "R1"))
        self.R1_Label.setText(_translate("MainWindow", "R1 = "))
        self.L2_Label.setText(_translate("MainWindow", "R2 = "))
        item = self.R2_Table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "R2"))
        self.devianceLabel.setText(_translate("MainWindow", "Deviance"))
        self.finalVoltageRatioLabel.setText(_translate("MainWindow", "Final Voltage Ratio"))
    
    #####
    basicCriteriaSignal = Signal(int, bool)
    
    def basicCriteriaChanged(self):
        sel = self.resistorCategoriesList.selectedItems()[0]
        match sel.text():
            case 'Chassis Mount Resistors':
                self.basicCriteriaSignal.emit(54, self.inStockCheckBox.isChecked())
            case 'Chip Resistor - Surface Mount':
                self.basicCriteriaSignal.emit(52, self.inStockCheckBox.isChecked())
            case 'Precision Trimmed Resistors':
                self.basicCriteriaSignal.emit(56, self.inStockCheckBox.isChecked())
            case 'Resistor Networks - Arrays':
                self.basicCriteriaSignal.emit(50, self.inStockCheckBox.isChecked())
            case 'Specialized Resistors':
                self.basicCriteriaSignal.emit(55, self.inStockCheckBox.isChecked())
            case 'Through Hole Resistors':
                self.basicCriteriaSignal.emit(53, self.inStockCheckBox.isChecked())
            case _:
                raise Exception('Something went wrong in the resistor category selection!')

    #####
    rohsSelectionSignal = Signal(bool)
    
    def rohsSelectionChanged(self):

        self.rohsSelectionSignal.emit(self.rohsCompliantCheckBox.isChecked())

    #####
    relationInputSignal = Signal(float)

    def relationInputChanged(self):

        self.relationInputSignal.emit(self.relationInputBox.value())


    #####
    comboBox_R1_Signal = Signal(str)
    comboBox_R2_Signal = Signal(str)

    def comboBox_R1_Changed(self):
        self.newCombo_R1_value = True
        if (self.newCombo_R2_value == False):
            self.comboBox_R2.setCurrentIndex(-1)
            self.comboBox_R1_Signal.emit(self.comboBox_R1.currentText())
        self.newCombo_R1_value = False

    def comboBox_R2_Changed(self):
        self.newCombo_R2_value = True
        if (self.newCombo_R1_value == False):
            self.comboBox_R1.setCurrentIndex(-1)
            self.comboBox_R2_Signal.emit(self.comboBox_R2.currentText())
        self.newCombo_R2_value = False


    #####
    searchSignal = Signal()
    
    def searchInitiated(self):
        self.R1_Table.clear()
        self.R2_Table.clear()
        self.finalVoltageRatioBox.clear()
        self.devianceBox.clear()
        self.searchSignal.emit()

    #####
    filtersSignal = Signal()
    
    def filtersClicked(self):

        self.filtersSignal.emit()

    def R1_SelectionChanged(self):
        
        if(len(self.R1_Table.selectedItems())==0):
            self.R1_SelectionExists = False
            self.recalculateDevianceAndFinal()
        else:
            self.R1_SelectionExists = True
            self.recalculateDevianceAndFinal()

    def R2_SelectionChanged(self):
        
        if(len(self.R2_Table.selectedItems())==0):
            self.R2_SelectionExists = False
            self.recalculateDevianceAndFinal()
        else:
            self.R2_SelectionExists = True
            self.recalculateDevianceAndFinal()

    def recalculateDevianceAndFinal(self):

        if(self.R1_SelectionExists and self.R2_SelectionExists):
            r1_InPico = resistance2NominalValueInPOhms(self.r1Json['Products'][self.R1_Table.selectedItems()[0].row()]['Parameters'][0]['ValueText'], Round=False)
            r2_InPico = resistance2NominalValueInPOhms(self.r2Json['Products'][self.R2_Table.selectedItems()[0].row()]['Parameters'][0]['ValueText'], Round=False)

            realH = r2_InPico / (r1_InPico + r2_InPico)
            self.finalVoltageRatioBox.setPlainText(str(realH))

            deviance = abs(realH - self.relationInputBox.value()) / self.relationInputBox.value()
            self.devianceBox.setPlainText(str(deviance))
        else:
            self.finalVoltageRatioBox.clear()
            self.devianceBox.clear()


    @Slot(list)
    def onResistorValuesCalculated(self, arg):
        self.statusbar.showMessage('API access completed', 5000)
        self.comboBox_R1.clear()
        self.comboBox_R2.clear()
        for value in arg:
            self.comboBox_R1.addItem(value)
            self.comboBox_R1.setCurrentIndex(-1)
            self.comboBox_R2.addItem(value)
            self.comboBox_R2.setCurrentIndex(-1)

    @Slot(dict, dict)
    def buildTables(self, r1, r2):
        self.statusbar.showMessage('Building the tables', 0)
        self.r1Json = r1
        self.r2Json = r2
        self.R1_Table.setRowCount(len(r1['Products']))
        self.R2_Table.setRowCount(len(r2['Products']))
        
        for row in range(len(r1['Products'])):
            product = r1['Products'][row]
            item = QtWidgets.QTableWidgetItem(product['Description']['ProductDescription'] + " (" + product['Parameters'][0]['ValueText'] + ")")
            self.R1_Table.setItem(row, 0, item)
        
        for row in range(len(r2['Products'])):
            product = r2['Products'][row]
            item = QtWidgets.QTableWidgetItem(product['Description']['ProductDescription'] + " (" + product['Parameters'][0]['ValueText'] + ")")
            self.R2_Table.setItem(row, 0, item)

        self.statusbar.showMessage('Table building completed', 5000)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
